# Generated by Django 5.0.6 on 2024-06-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_remove_detallecompra_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
