# Generated by Django 5.0.6 on 2024-06-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_producto_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='CarritoItem',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
